//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XISOExtractorGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XISOExtractorGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string AbortBtnText {
            get {
                return ResourceManager.GetString("AbortBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Queue.
        /// </summary>
        internal static string AddToQueueBtnText {
            get {
                return ResourceManager.GetString("AddToQueueBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0} on port {1}.
        /// </summary>
        internal static string ConnectingToOnPort {
            get {
                return ResourceManager.GetString("ConnectingToOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed... waiting for further instructions....
        /// </summary>
        internal static string DoneWaitingForFurtherInstructions {
            get {
                return ResourceManager.GetString("DoneWaitingForFurtherInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to open
        ///{0}
        ///For read, if it&apos;s open in any other program close that and press Retry!.
        /// </summary>
        internal static string ErrorLoadingFileTryAgain {
            get {
                return ResourceManager.GetString("ErrorLoadingFileTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERRORTitle {
            get {
                return ResourceManager.GetString("ERRORTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed.
        /// </summary>
        internal static string ExtractFailed {
            get {
                return ResourceManager.GetString("ExtractFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Transfer ERROR.
        /// </summary>
        internal static string FTPTransferErrorTitle {
            get {
                return ResourceManager.GetString("FTPTransferErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Directory information from: {0}.
        /// </summary>
        internal static string GettingDirInfoFTP {
            get {
                return ResourceManager.GetString("GettingDirInfoFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Root directory information....
        /// </summary>
        internal static string GettingRootDirInfoFTP {
            get {
                return ResourceManager.GetString("GettingRootDirInfoFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more extractions failed! Press Ok to get a list of the results....
        /// </summary>
        internal static string MultiExtractFailed {
            get {
                return ResourceManager.GetString("MultiExtractFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted by user!.
        /// </summary>
        internal static string OperationAbortedByUser {
            get {
                return ResourceManager.GetString("OperationAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while transfering {0}:
        ///{1}.
        /// </summary>
        internal static string XISOFTPTransferError {
            get {
                return ResourceManager.GetString("XISOFTPTransferError", resourceCulture);
            }
        }
    }
}
